# Generated by Django 4.2.10 on 2025-01-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
