# Generated by Django 4.2.10 on 2025-01-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('meeting_number', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('join_url', models.CharField(max_length=255)),
                ('start_url', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('goal', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner_image_url', models.ImageField(blank=True, null=True, upload_to='session_banner_images/', verbose_name='Session Banner Image')),
                ('total_participant_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('equipments', models.JSONField(blank=True, null=True)),
                ('booked_users', models.ManyToManyField(related_name='booked_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Booked Users')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL, verbose_name='Session Creator')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.meeting', verbose_name='')),
            ],
        ),
    ]
