# Generated by Django 4.2.10 on 2025-02-10 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_alter_class_calorie_per_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('meeting_number', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('join_url', models.TextField()),
                ('start_url', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('goal', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='session_banner_images/', verbose_name='Session Banner Image')),
                ('current_participant_number', models.IntegerField(default=0)),
                ('total_participant_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('equipments', models.JSONField(blank=True, null=True)),
                ('booked_users', models.ManyToManyField(related_name='booked_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Booked Users')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL, verbose_name='Session Creator')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.meeting', verbose_name='session_meeting')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('calorie', models.IntegerField()),
                ('total_participant_number', models.IntegerField()),
                ('equipments', models.JSONField(blank=True, null=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_class', to='classes.class', verbose_name='Using Class')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.meeting', verbose_name='class_session_meeting')),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
            },
        ),
    ]
