# Generated by Django 4.2.10 on 2025-01-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='banner_image_url',
            new_name='banner_image',
        ),
    ]
