# Generated by Django 4.2.10 on 2025-02-01 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_banner_image'),
        ('session', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session.session')),
                ('used_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_class', to='classes.class', verbose_name='Using Class')),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
            },
            bases=('session.session',),
        ),
    ]
