# Generated by Django 4.2.10 on 2025-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_classsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsession',
            old_name='used_class',
            new_name='class_ref',
        ),
        migrations.AddField(
            model_name='classsession',
            name='calorie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
