# Generated by Django 4.2.10 on 2025-01-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_rename_banner_image_url_session_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_participant_number',
            field=models.IntegerField(default=0),
        ),
    ]
