# Generated by Django 4.2.10 on 2025-01-29 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutDailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Daily Plan',
                'verbose_name_plural': 'Daily Plans',
            },
        ),
        migrations.CreateModel(
            name='ClientWorkout',
            fields=[
                ('workout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.workout')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Workout',
                'verbose_name_plural': 'Client Workouts',
            },
            bases=('workouts.workout',),
        ),
    ]
