# Generated by Django 4.2.10 on 2025-01-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWorkout',
            fields=[
                ('workout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.workout')),
            ],
            bases=('workouts.workout',),
        ),
        migrations.CreateModel(
            name='ClassWorkoutDailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Class Workout Daily Plan',
                'verbose_name_plural': 'Class Worktout Daily Plans',
            },
        ),
        migrations.CreateModel(
            name='ClientWorkoutDailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Client Workout Daily Plan',
                'verbose_name_plural': 'Client Workout Daily Plans',
            },
        ),
        migrations.RemoveField(
            model_name='workoutdailyplan',
            name='workout',
        ),
    ]
