# Generated by Django 4.2.10 on 2025-01-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_workoutexercise_daily_plan'),
        ('workouts', '0002_classworkout_classworkoutdailyplan_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutDailyPlan',
        ),
        migrations.AddField(
            model_name='clientworkoutdailyplan',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_workout_daily_plans', to='workouts.clientworkout'),
        ),
        migrations.AddField(
            model_name='classworkoutdailyplan',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_workout_daily_plans', to='workouts.classworkout'),
        ),
        migrations.AddField(
            model_name='classworkout',
            name='used_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_workouts', to='classes.class'),
        ),
    ]
