# Generated by Django 4.2.10 on 2025-02-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_rename_calorie_exercise_calorie_per_round_and_more'),
        ('workouts', '0003_delete_workoutdailyplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classworkoutdailyplan',
            name='workout',
        ),
        migrations.DeleteModel(
            name='ClassWorkout',
        ),
        migrations.DeleteModel(
            name='ClassWorkoutDailyPlan',
        ),
    ]
