# Generated by Django 4.2.10 on 2025-01-29 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('intensity', models.CharField(max_length=50, verbose_name='Intensity')),
                ('level', models.CharField(max_length=50, verbose_name='Level')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('session_count', models.PositiveIntegerField(verbose_name='Session Count')),
                ('duration_per_session', models.PositiveIntegerField(verbose_name='Duration per Session (minutes)')),
                ('calorie_per_session', models.PositiveIntegerField(verbose_name='Calorie Burn per Session')),
                ('benefits', models.JSONField(blank=True, default=list, verbose_name='Benefits')),
                ('equipments', models.JSONField(blank=True, default=list, verbose_name='Equipments')),
                ('booked_users', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'Client'}, related_name='booked_classes', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'user_type': 'Coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
