# Generated by Django 4.2.10 on 2025-02-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='session_banner_images/', verbose_name='Session Banner Image'),
        ),
    ]
