# Generated by Django 4.2.10 on 2025-02-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='calorie_per_session',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorie Burn per Session'),
        ),
        migrations.AlterField(
            model_name='class',
            name='duration_per_session',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration per Session (minutes)'),
        ),
        migrations.AlterField(
            model_name='class',
            name='session_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Session Count'),
        ),
    ]
