# Generated by Django 4.2.10 on 2025-01-29 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'Coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='review_content')),
                ('coach', models.ForeignKey(limit_choices_to={'user_type': 'Coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_coach', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(limit_choices_to={'user_type': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
