# Generated by Django 4.2.10 on 2025-01-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calorie',
            field=models.PositiveIntegerField(default=5, verbose_name='Calorie Burnt per one time'),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_count', models.PositiveIntegerField(default=3, verbose_name='Set Count')),
                ('reps_count', models.PositiveIntegerField(default=10, verbose_name='Reps Count')),
                ('rest_duration', models.PositiveIntegerField(default=30, verbose_name='Rest Duration (seconds)')),
                ('calorie', models.PositiveIntegerField(default=50, verbose_name='Calorie Burnt per Set')),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workoutdailyplan')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_instances', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workout Exercises',
            },
        ),
    ]
