# Generated by Django 4.2.10 on 2025-02-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_rename_calorie_exercise_calorie_per_round_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classexercise',
            old_name='exercise',
            new_name='exercise_ref',
        ),
    ]
