# Generated by Django 4.2.10 on 2025-02-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_calorie_per_session_and_more'),
        ('exercises', '0005_rename_exercise_classexercise_exercise_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexercise',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_ref', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='classexercise',
            name='exercise_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_ref', to='exercises.exercise'),
        ),
    ]
